### ISSUE TITLE
Why is $remotedb hard-coded to mysqli_native_moodle_database?

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#3] opened 2015-02-12 15:58 UTC
If you achieve to make the code cross-db compatible (as reported in #1), it would make sense to make the remote DB engine configurable, too. You may want to use the same DB engine selector that the Moodle installer has.

**Comment by jgramp** [comment] 2015-02-19 10:38
Made code cross-db compatible - the remote DB will use the same db type as the Moodle $DB object, since the external database is expected to be an exact duplicate of the Moodle DB. Changes implemented in version 1.2.

**Closed as completed by jgramp** 2015-02-19 10:38 UTC
